spring:
 cloud:
  gateway:
   globlalcors:
    cors-configuration:
     '[/**]':
       allowedOrigins: "http://localhost:4200"
       allowedMethos: GET, POST, PUT, DELETE
       allowedHeaders: "*"
       allowCredentials: true